class_name SignalBus
#signal.gd
extends Node2D

signal dialogue1_finished
signal dialogue2_finished
signal dialogue3_finished
signal dialogue4_finished
signal player_talked
signal tutorial_guy_talked
signal boss_talked
signal interaction_shown
signal interaction_hidden
signal player_attacked
signal player_succeed
signal player_failed
signal enemy_attacked
signal enemy_succeed
signal enemy_failed
signal battle_ended
